### ISSUE TITLE
Factor out remaining ACPI tables into arm64

### ISSUE THREAD

**Issue by CodingVoid** [9elements/u-boot-acpi#1]
DBG2, SPCR and FADT have already been factored out (from x86 and raspberry pi code) into common code.
Move the remaining tables to common and or architecture code and only leave the raspberry pi specific bits in board code.

**Comment by PatrickRudolph** [comment]
Moved some parts to SoC code here: https://github.com/9elements/u-boot-acpi/commit/6fac0ddb6e4cc87502879ca90f1d792048b982b8

**Comment by PatrickRudolph** [comment]
Done in https://github.com/9elements/u-boot-acpi/commit/8645ef2d8dd28dcef1f72c360a8c3abf687f98a7
