### ISSUE TITLE
CLEANUP:  arm: cpu: Add ACPI parking protocol support 

### ISSUE THREAD

**Issue by PatrickRudolph** [9elements/u-boot-acpi#13]
**Commit**

https://github.com/9elements/u-boot-acpi/commit/3c2cb519d508d9b0df57b91b1e41c8e862e44f6a

**Requested changes**

1. Rename file to `acpi_park_v8.S`
2. ```
     acpi_park_code_size
     acpi_parking_protocol
     ```
     is too long
3. ```
    > +       .word __secondary_parking_protocol_code_end - __secondary_parking_protocol_code_start
    Is there a 'primary'? Does this refer to the code run by the secondary CPUs?
    ```
4. ```
    extern u32 acpi_parking_protocol_code_size;
    u32 but it says .word in the code...isn't that 16 bits?
    ```
5. ``` > +               memset(page, 0, sizeof(struct acpi_parking_protocol_page));```
    -> memset(page, '\0', ...
6. ```
   > +
   > +       /* Prepare the parking protocol pages */
   > +       for (int i = sizeof(struct acpi_madt); i < madt->header.length; ) {
   
   please use 'pos' instead of 'i' as this isn't really an index
   
   > +               gicc = (struct acpi_madt_gicc *)((void *)madt + i);
   
   Can you put the loop code in a separate function? This is getting a
   bit long for one function
   ```
7. ```
   > +
   > +#if CONFIG_IS_ENABLED(EFI_LOADER)
   > +       int ret = efi_add_memory_map(start, ncpus * ACPI_PP_PAGE_SIZE, EFI_RESERVED_MEMORY_TYPE);
   > +
   > +       if (ret != EFI_SUCCESS)
   > +               log_err("Reserved memory mapping failed addr %llx size %x\n",
   > +                       start, ncpus * ACPI_PP_PAGE_SIZE);
   > +#endif

   This map will overlap the one that EFI creates for the malloc()
   region, won't it?
   ```
8. ```
   > +       /* Allocate pages linearly due to assembly code requirements */
   > +       page = memalign(ACPI_PP_PAGE_SIZE, ACPI_PP_PAGE_SIZE * ncpus);
   > +       start = (u64)(uintptr_t)page;
   
   Again, this should go in the bloblist.
   ```

**Comment by siro20** [comment]
Resolved with https://github.com/9elements/u-boot-acpi/commit/769e07a44dcecd056346490bce84171a938a8e22

**Comment by PatrickRudolph** [comment]
Fixed with https://github.com/9elements/u-boot-acpi/commit/769e07a44dcecd056346490bce84171a938a8e22
