### ISSUE TITLE
Tell Linux to use the SPCR console as /dev/console

### ISSUE THREAD

**Issue by CodingVoid** [9elements/u-boot-acpi#3]
Currently Linux jumps into u-root, but u-root immediatly kills itself, since it cannot open /dev/console (since it does not exist).
For some reason the console in SPCR/DBG2 Table is not used as console. May just need the correct kernel parameter to work.

**Comment by PatrickRudolph** [comment]
Works in https://github.com/9elements/u-boot-acpi/commit/6fac0ddb6e4cc87502879ca90f1d792048b982b8
