### ISSUE TITLE
Remove EDK2 fragments

### ISSUE THREAD

**Issue by CodingVoid** [9elements/u-boot-acpi#4]
The original patch from Simon basically copied  most ACPI related files from EDK2 into u-boot. They are good as a reference, but since u-boot does not use them they need to be removed at some point.

**Comment by PatrickRudolph** [comment]
Starting code cleanup here: https://github.com/9elements/u-boot-acpi/commit/6fac0ddb6e4cc87502879ca90f1d792048b982b8

**Comment by PatrickRudolph** [comment]
Done in https://github.com/9elements/u-boot-acpi/commit/8645ef2d8dd28dcef1f72c360a8c3abf687f98a7
